targets:
  $default:
    builders:
      json_serializable:
        options:
          checked: true # false -> true
          explicit_to_json: true # false -> true
      freezed:
        options: 
          format: false
      flutter_gen:
        options:
          output: lib/core/res/gen