targets:
  $default:
    builders:
      json_serializable:
        options:
          checked: true # false -> true
          explicit_to_json: true # false -> true
          field_rename: snake
        generate_for:
          include:
            - lib/entities/**/*.dart
            - lib/firebase/*/entities/*.dart
            - lib/features/**/entities/*.dart
      freezed:
        options: 
          format: false
        generate_for:
          include:
            - lib/**/entities/**/*.dart
            - lib/**/entities/*.dart
      riverpod_generator:
        generate_for:
          include:
            - lib/**/repositories/**/*.dart
            - lib/**/use_cases/**/*.dart
            - lib/repositories/**/*.dart
            - lib/core/router/root.dart
      flutter_gen:
        options:
          output: lib/core/res/gen