name: cheers_planner
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  async: ^2.11.0
  clock: ^1.1.1
  cloud_firestore: ^5.4.4
  cloud_functions: ^5.1.5
  collection: ^1.18.0
  firebase_auth: ^5.3.1
  firebase_core: ^3.8.1
  firebase_storage: ^12.3.7
  firebase_ui_auth: ^1.16.1
  firebase_ui_firestore: ^1.7.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.2
  flutter_web_plugins:
    sdk: flutter
  freezed_annotation: ^3.0.0
  gap: ^3.0.1
  go_router: ^15.0.0
  hooks_riverpod: ^2.5.4
  json_annotation: ^4.9.0
  package_info_plus: ^8.1.0
  riverpod_annotation: ^2.5.3
  shared_preferences: ^2.5.2
  zod_validation: ^1.0.5

dev_dependencies:
  build_runner: ^2.4.13
  build_verify: ^3.1.0
  fake_async: ^1.3.1
  fake_cloud_firestore: ^3.1.0
  firebase_auth_mocks: ^0.14.1
  flutter_gen_runner: ^5.8.0
  flutter_launcher_icons: ^0.14.3
  flutter_test:
    sdk: flutter
  freezed: ^3.0.4
  go_router_builder: ^2.7.1
  json_serializable: ^6.8.0
  mocktail: ^1.0.4
  pedantic_mono: ^1.29.0
  riverpod_generator: ^2.4.3
  riverpod_lint: ^2.3.13
  test: ^1.25.8

flutter:
  generate: true
  uses-material-design: true