#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Flutter format check and analyze
(cd flutter && dart format . --set-exit-if-changed && flutter analyze)
# Firebase functions lint staged
npm --prefix firebase/functions run lint-staged
