name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main
    paths:
      - 'flutter/**'
      - 'hosting/**'
      - '.github/workflows/firebase-hosting-pull-request.yml'
      - '.github/workflows/firebase-hosting-merge.yml'
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Flutter
        uses: ./.github/actions/setup_flutter
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_CHEERS_PLANNER }}
          channelId: live
          projectId: cheers-planner
          entryPoint: hosting/
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks

